<?php
// includes/nationality_map.php

function getNationalityMap()
{
    return [
        'Afghanistan' => ['ar' => 'أفغانستان', 'en' => 'Afghanistan'],
        'Albania' => ['ar' => 'ألبانيا', 'en' => 'Albania'],
        'Algeria' => ['ar' => 'الجزائر', 'en' => 'Algeria'],
        'Andorra' => ['ar' => 'أندورا', 'en' => 'Andorra'],
        'Angola' => ['ar' => 'أنغولا', 'en' => 'Angola'],
        'Antigua and Barbuda' => ['ar' => 'أنتيغوا وبربودا', 'en' => 'Antigua and Barbuda'],
        'Argentina' => ['ar' => 'الأرجنتين', 'en' => 'Argentina'],
        'Armenia' => ['ar' => 'أرمينيا', 'en' => 'Armenia'],
        'Australia' => ['ar' => 'أستراليا', 'en' => 'Australia'],
        'Austria' => ['ar' => 'النمسا', 'en' => 'Austria'],
        'Azerbaijan' => ['ar' => 'أذربيجان', 'en' => 'Azerbaijan'],
        'Bahamas' => ['ar' => 'جزر البهاما', 'en' => 'Bahamas'],
        'Bahrain' => ['ar' => 'البحرين', 'en' => 'Bahrain'],
        'Bangladesh' => ['ar' => 'بنغلاديش', 'en' => 'Bangladesh'],
        'Barbados' => ['ar' => 'بربادوس', 'en' => 'Barbados'],
        'Belarus' => ['ar' => 'بيلاروسيا', 'en' => 'Belarus'],
        'Belgium' => ['ar' => 'بلجيكا', 'en' => 'Belgium'],
        'Belize' => ['ar' => 'بليز', 'en' => 'Belize'],
        'Benin' => ['ar' => 'بنين', 'en' => 'Benin'],
        'Bhutan' => ['ar' => 'بوتان', 'en' => 'Bhutan'],
        'Bolivia' => ['ar' => 'بوليفيا', 'en' => 'Bolivia'],
        'Bosnia and Herzegovina' => ['ar' => 'البوسنة والهرسك', 'en' => 'Bosnia and Herzegovina'],
        'Botswana' => ['ar' => 'بوتسوانا', 'en' => 'Botswana'],
        'Brazil' => ['ar' => 'البرازيل', 'en' => 'Brazil'],
        'Brunei' => ['ar' => 'بروناي', 'en' => 'Brunei'],
        'Bulgaria' => ['ar' => 'بلغاريا', 'en' => 'Bulgaria'],
        'Burkina Faso' => ['ar' => 'بوركينا فاسو', 'en' => 'Burkina Faso'],
        'Burundi' => ['ar' => 'بوروندي', 'en' => 'Burundi'],
        'Cabo Verde' => ['ar' => 'الرأس الأخضر', 'en' => 'Cabo Verde'],
        'Cambodia' => ['ar' => 'كمبوديا', 'en' => 'Cambodia'],
        'Cameroon' => ['ar' => 'الكاميرون', 'en' => 'Cameroon'],
        'Canada' => ['ar' => 'كندا', 'en' => 'Canada'],
        'Central African Republic' => ['ar' => 'جمهورية أفريقيا الوسطى', 'en' => 'Central African Republic'],
        'Chad' => ['ar' => 'تشاد', 'en' => 'Chad'],
        'Chile' => ['ar' => 'تشيلي', 'en' => 'Chile'],
        'China' => ['ar' => 'الصين', 'en' => 'China'],
        'Colombia' => ['ar' => 'كولومبيا', 'en' => 'Colombia'],
        'Comoros' => ['ar' => 'جزر القمر', 'en' => 'Comoros'],
        'Congo' => ['ar' => 'الكونغو', 'en' => 'Congo'],
        'Costa Rica' => ['ar' => 'كوستاريكا', 'en' => 'Costa Rica'],
        'Croatia' => ['ar' => 'كرواتيا', 'en' => 'Croatia'],
        'Cuba' => ['ar' => 'كوبا', 'en' => 'Cuba'],
        'Cyprus' => ['ar' => 'قبرص', 'en' => 'Cyprus'],
        'Czech Republic' => ['ar' => 'جمهورية التشيك', 'en' => 'Czech Republic'],
        'Denmark' => ['ar' => 'الدانمارك', 'en' => 'Denmark'],
        'Djibouti' => ['ar' => 'جيبوتي', 'en' => 'Djibouti'],
        'Dominica' => ['ar' => 'دومينيكا', 'en' => 'Dominica'],
        'Dominican Republic' => ['ar' => 'جمهورية الدومينيكان', 'en' => 'Dominican Republic'],
        'Ecuador' => ['ar' => 'الإكوادور', 'en' => 'Ecuador'],
        'Egypt' => ['ar' => 'مصر', 'en' => 'Egypt'],
        'El Salvador' => ['ar' => 'السلفادور', 'en' => 'El Salvador'],
        'Equatorial Guinea' => ['ar' => 'غينيا الاستوائية', 'en' => 'Equatorial Guinea'],
        'Eritrea' => ['ar' => 'إريتريا', 'en' => 'Eritrea'],
        'Estonia' => ['ar' => 'إستونيا', 'en' => 'Estonia'],
        'Eswatini' => ['ar' => 'إسواتيني', 'en' => 'Eswatini'],
        'Ethiopia' => ['ar' => 'إثيوبيا', 'en' => 'Ethiopia'],
        'Fiji' => ['ar' => 'فيجي', 'en' => 'Fiji'],
        'Finland' => ['ar' => 'فنلندا', 'en' => 'Finland'],
        'France' => ['ar' => 'فرنسا', 'en' => 'France'],
        'Gabon' => ['ar' => 'الغابون', 'en' => 'Gabon'],
        'Gambia' => ['ar' => 'غامبيا', 'en' => 'Gambia'],
        'Georgia' => ['ar' => 'جورجيا', 'en' => 'Georgia'],
        'Germany' => ['ar' => 'ألمانيا', 'en' => 'Germany'],
        'Ghana' => ['ar' => 'غانا', 'en' => 'Ghana'],
        'Greece' => ['ar' => 'اليونان', 'en' => 'Greece'],
        'Grenada' => ['ar' => 'غرينادا', 'en' => 'Grenada'],
        'Guatemala' => ['ar' => 'غواتيمالا', 'en' => 'Guatemala'],
        'Guinea' => ['ar' => 'غينيا', 'en' => 'Guinea'],
        'Guinea-Bissau' => ['ar' => 'غينيا بيساو', 'en' => 'Guinea-Bissau'],
        'Guyana' => ['ar' => 'غيانا', 'en' => 'Guyana'],
        'Haiti' => ['ar' => 'هايتي', 'en' => 'Haiti'],
        'Honduras' => ['ar' => 'هندوراس', 'en' => 'Honduras'],
        'Hungary' => ['ar' => 'هنغاريا', 'en' => 'Hungary'],
        'Iceland' => ['ar' => 'آيسلندا', 'en' => 'Iceland'],
        'India' => ['ar' => 'الهند', 'en' => 'India'],
        'Indonesia' => ['ar' => 'إندونيسيا', 'en' => 'Indonesia'],
        'Iran' => ['ar' => 'إيران', 'en' => 'Iran'],
        'Iraq' => ['ar' => 'العراق', 'en' => 'Iraq'],
        'Ireland' => ['ar' => 'أيرلندا', 'en' => 'Ireland'],
        'Italy' => ['ar' => 'إيطاليا', 'en' => 'Italy'],
        'Jamaica' => ['ar' => 'جامايكا', 'en' => 'Jamaica'],
        'Japan' => ['ar' => 'اليابان', 'en' => 'Japan'],
        'Jordan' => ['ar' => 'الأردن', 'en' => 'Jordan'],
        'Kazakhstan' => ['ar' => 'كازاخستان', 'en' => 'Kazakhstan'],
        'Kenya' => ['ar' => 'كينيا', 'en' => 'Kenya'],
        'Kiribati' => ['ar' => 'كيريباتي', 'en' => 'Kiribati'],
        'Korea, North' => ['ar' => 'كوريا الشمالية', 'en' => 'North Korea'],
        'Korea, South' => ['ar' => 'كوريا الجنوبية', 'en' => 'South Korea'],
        'Kosovo' => ['ar' => 'كوسوفو', 'en' => 'Kosovo'],
        'Kuwait' => ['ar' => 'الكويت', 'en' => 'Kuwait'],
        'Kyrgyzstan' => ['ar' => 'قرغيزستان', 'en' => 'Kyrgyzstan'],
        'Laos' => ['ar' => 'لاوس', 'en' => 'Laos'],
        'Latvia' => ['ar' => 'لاتفيا', 'en' => 'Latvia'],
        'Lebanon' => ['ar' => 'لبنان', 'en' => 'Lebanon'],
        'Lesotho' => ['ar' => 'ليسوتو', 'en' => 'Lesotho'],
        'Liberia' => ['ar' => 'ليبيريا', 'en' => 'Liberia'],
        'Libya' => ['ar' => 'ليبيا', 'en' => 'Libya'],
        'Liechtenstein' => ['ar' => 'ليختنشتاين', 'en' => 'Liechtenstein'],
        'Lithuania' => ['ar' => 'ليتوانيا', 'en' => 'Lithuania'],
        'Luxembourg' => ['ar' => 'لوكسمبورغ', 'en' => 'Luxembourg'],
        'Madagascar' => ['ar' => 'مدغشقر', 'en' => 'Madagascar'],
        'Malawi' => ['ar' => 'مالاوي', 'en' => 'Malawi'],
        'Malaysia' => ['ar' => 'ماليزيا', 'en' => 'Malaysia'],
        'Maldives' => ['ar' => 'المالديف', 'en' => 'Maldives'],
        'Mali' => ['ar' => 'مالي', 'en' => 'Mali'],
        'Malta' => ['ar' => 'مالطا', 'en' => 'Malta'],
        'Marshall Islands' => ['ar' => 'جزر مارشال', 'en' => 'Marshall Islands'],
        'Mauritania' => ['ar' => 'موريتانيا', 'en' => 'Mauritania'],
        'Mauritius' => ['ar' => 'موريشيوس', 'en' => 'Mauritius'],
        'Mexico' => ['ar' => 'المكسيك', 'en' => 'Mexico'],
        'Micronesia' => ['ar' => 'ميكرونيزيا', 'en' => 'Micronesia'],
        'Moldova' => ['ar' => 'مولدوفا', 'en' => 'Moldova'],
        'Monaco' => ['ar' => 'موناكو', 'en' => 'Monaco'],
        'Mongolia' => ['ar' => 'منغوليا', 'en' => 'Mongolia'],
        'Montenegro' => ['ar' => 'الجبل الأسود', 'en' => 'Montenegro'],
        'Morocco' => ['ar' => 'المغرب', 'en' => 'Morocco'],
        'Mozambique' => ['ar' => 'موزمبيق', 'en' => 'Mozambique'],
        'Myanmar' => ['ar' => 'ميانمار', 'en' => 'Myanmar'],
        'Namibia' => ['ar' => 'ناميبيا', 'en' => 'Namibia'],
        'Nauru' => ['ar' => 'ناورو', 'en' => 'Nauru'],
        'Nepal' => ['ar' => 'نيبال', 'en' => 'Nepal'],
        'Netherlands' => ['ar' => 'هولندا', 'en' => 'Netherlands'],
        'New Zealand' => ['ar' => 'نيوزيلندا', 'en' => 'New Zealand'],
        'Nicaragua' => ['ar' => 'نيكاراغوا', 'en' => 'Nicaragua'],
        'Niger' => ['ar' => 'النيجر', 'en' => 'Niger'],
        'Nigeria' => ['ar' => 'نيجيريا', 'en' => 'Nigeria'],
        'North Macedonia' => ['ar' => 'مقدونيا الشمالية', 'en' => 'North Macedonia'],
        'Norway' => ['ar' => 'النرويج', 'en' => 'Norway'],
        'Oman' => ['ar' => 'عمان', 'en' => 'Oman'],
        'Pakistan' => ['ar' => 'باكستان', 'en' => 'Pakistan'],
        'Palau' => ['ar' => 'بالاو', 'en' => 'Palau'],
        'Palestine' => ['ar' => 'فلسطين', 'en' => 'Palestine'],
        'Panama' => ['ar' => 'بنما', 'en' => 'Panama'],
        'Papua New Guinea' => ['ar' => 'بابوا غينيا الجديدة', 'en' => 'Papua New Guinea'],
        'Paraguay' => ['ar' => 'باراغواي', 'en' => 'Paraguay'],
        'Peru' => ['ar' => 'بيرو', 'en' => 'Peru'],
        'Philippines' => ['ar' => 'الفلبين', 'en' => 'Philippines'],
        'Poland' => ['ar' => 'بولندا', 'en' => 'Poland'],
        'Portugal' => ['ar' => 'البرتغال', 'en' => 'Portugal'],
        'Qatar' => ['ar' => 'قطر', 'en' => 'Qatar'],
        'Romania' => ['ar' => 'رومانيا', 'en' => 'Romania'],
        'Russia' => ['ar' => 'روسيا', 'en' => 'Russia'],
        'Rwanda' => ['ar' => 'رواندا', 'en' => 'Rwanda'],
        'Saint Kitts and Nevis' => ['ar' => 'سانت كيتس ونيفيس', 'en' => 'Saint Kitts and Nevis'],
        'Saint Lucia' => ['ar' => 'سانت لوسيا', 'en' => 'Saint Lucia'],
        'Saint Vincent and the Grenadines' => ['ar' => 'سانت فنسنت وجزر غرينادين', 'en' => 'Saint Vincent and the Grenadines'],
        'Samoa' => ['ar' => 'ساموا', 'en' => 'Samoa'],
        'San Marino' => ['ar' => 'سان مارينو', 'en' => 'San Marino'],
        'Sao Tome and Principe' => ['ar' => 'ساو تومي وبرينسيب', 'en' => 'Sao Tome and Principe'],
        'Saudi Arabia' => ['ar' => 'المملكة العربية السعودية', 'en' => 'Saudi Arabia'],
        'Senegal' => ['ar' => 'السنغال', 'en' => 'Senegal'],
        'Serbia' => ['ar' => 'صربيا', 'en' => 'Serbia'],
        'Seychelles' => ['ar' => 'سيشيل', 'en' => 'Seychelles'],
        'Sierra Leone' => ['ar' => 'سيراليون', 'en' => 'Sierra Leone'],
        'Singapore' => ['ar' => 'سنغافورة', 'en' => 'Singapore'],
        'Slovakia' => ['ar' => 'سلوفاكيا', 'en' => 'Slovakia'],
        'Slovenia' => ['ar' => 'سلوفينيا', 'en' => 'Slovenia'],
        'Solomon Islands' => ['ar' => 'جزر سليمان', 'en' => 'Solomon Islands'],
        'Somalia' => ['ar' => 'الصومال', 'en' => 'Somalia'],
        'South Africa' => ['ar' => 'جنوب أفريقيا', 'en' => 'South Africa'],
        'South Sudan' => ['ar' => 'جنوب السودان', 'en' => 'South Sudan'],
        'Spain' => ['ar' => 'إسبانيا', 'en' => 'Spain'],
        'Sri Lanka' => ['ar' => 'سريلانكا', 'en' => 'Sri Lanka'],
        'Sudan' => ['ar' => 'السودان', 'en' => 'Sudan'],
        'Suriname' => ['ar' => 'سورينام', 'en' => 'Suriname'],
        'Sweden' => ['ar' => 'السويد', 'en' => 'Sweden'],
        'Switzerland' => ['ar' => 'سويسرا', 'en' => 'Switzerland'],
        'Syria' => ['ar' => 'سوريا', 'en' => 'Syria'],
        'Taiwan' => ['ar' => 'تايوان', 'en' => 'Taiwan'],
        'Tajikistan' => ['ar' => 'طاجيكستان', 'en' => 'Tajikistan'],
        'Tanzania' => ['ar' => 'تنزانيا', 'en' => 'Tanzania'],
        'Thailand' => ['ar' => 'تايلاند', 'en' => 'Thailand'],
        'Timor-Leste' => ['ar' => 'تيمور الشرقية', 'en' => 'Timor-Leste'],
        'Togo' => ['ar' => 'توغو', 'en' => 'Togo'],
        'Tonga' => ['ar' => 'تونغا', 'en' => 'Tonga'],
        'Trinidad and Tobago' => ['ar' => 'ترينيداد وتوباغو', 'en' => 'Trinidad and Tobago'],
        'Tunisia' => ['ar' => 'تونس', 'en' => 'Tunisia'],
        'Turkey' => ['ar' => 'تركيا', 'en' => 'Turkey'],
        'Turkmenistan' => ['ar' => 'تركمانستان', 'en' => 'Turkmenistan'],
        'Tuvalu' => ['ar' => 'توفالو', 'en' => 'Tuvalu'],
        'Uganda' => ['ar' => 'أوغندا', 'en' => 'Uganda'],
        'Ukraine' => ['ar' => 'أوكرانيا', 'en' => 'Ukraine'],
        'United Arab Emirates' => ['ar' => 'الإمارات العربية المتحدة', 'en' => 'United Arab Emirates'],
        'United Kingdom' => ['ar' => 'المملكة المتحدة', 'en' => 'United Kingdom'],
        'United States' => ['ar' => 'الولايات المتحدة', 'en' => 'United States'],
        'Uruguay' => ['ar' => 'أوروغواي', 'en' => 'Uruguay'],
        'Uzbekistan' => ['ar' => 'أوزبكستان', 'en' => 'Uzbekistan'],
        'Vanuatu' => ['ar' => 'فانواتو', 'en' => 'Vanuatu'],
        'Vatican City' => ['ar' => 'الفاتيكان', 'en' => 'Vatican City'],
        'Venezuela' => ['ar' => 'فنزويلا', 'en' => 'Venezuela'],
        'Vietnam' => ['ar' => 'فيتنام', 'en' => 'Vietnam'],
        'Yemen' => ['ar' => 'اليمن', 'en' => 'Yemen'],
        'Zambia' => ['ar' => 'زامبيا', 'en' => 'Zambia'],
        'Zimbabwe' => ['ar' => 'زيمبابوي', 'en' => 'Zimbabwe'],

        // Nationalities (Adjectives) - Mapping to Country
        'Afghan' => ['ar' => 'أفغانستان', 'en' => 'Afghanistan'],
        'Albanian' => ['ar' => 'ألبانيا', 'en' => 'Albania'],
        'Algerian' => ['ar' => 'الجزائر', 'en' => 'Algeria'],
        'American' => ['ar' => 'الولايات المتحدة', 'en' => 'United States'],
        'Andorran' => ['ar' => 'أندورا', 'en' => 'Andorra'],
        'Angolan' => ['ar' => 'أنغولا', 'en' => 'Angola'],
        'Argentine' => ['ar' => 'الأرجنتين', 'en' => 'Argentina'],
        'Armenian' => ['ar' => 'أرمينيا', 'en' => 'Armenia'],
        'Australian' => ['ar' => 'أستراليا', 'en' => 'Australia'],
        'Austrian' => ['ar' => 'النمسا', 'en' => 'Austria'],
        'Azerbaijani' => ['ar' => 'أذربيجان', 'en' => 'Azerbaijan'],
        'Bahraini' => ['ar' => 'البحرين', 'en' => 'Bahrain'],
        'Bangladeshi' => ['ar' => 'بنغلاديش', 'en' => 'Bangladesh'],
        'Barbadian' => ['ar' => 'بربادوس', 'en' => 'Barbados'],
        'Belarusian' => ['ar' => 'بيلاروسيا', 'en' => 'Belarus'],
        'Belgian' => ['ar' => 'بلجيكا', 'en' => 'Belgium'],
        'Belizean' => ['ar' => 'بليز', 'en' => 'Belize'],
        'Beninese' => ['ar' => 'بنين', 'en' => 'Benin'],
        'Bhutanese' => ['ar' => 'بوتان', 'en' => 'Bhutan'],
        'Bolivian' => ['ar' => 'بوليفيا', 'en' => 'Bolivia'],
        'Bosnian' => ['ar' => 'البوسنة والهرسك', 'en' => 'Bosnia and Herzegovina'],
        'Motswana' => ['ar' => 'بوتسوانا', 'en' => 'Botswana'],
        'Brazilian' => ['ar' => 'البرازيل', 'en' => 'Brazil'],
        'Bruneian' => ['ar' => 'بروناي', 'en' => 'Brunei'],
        'Bulgarian' => ['ar' => 'بلغاريا', 'en' => 'Bulgaria'],
        'Burkinabe' => ['ar' => 'بوركينا فاسو', 'en' => 'Burkina Faso'],
        'Burundian' => ['ar' => 'بوروندي', 'en' => 'Burundi'],
        'Cabo Verdean' => ['ar' => 'الرأس الأخضر', 'en' => 'Cabo Verde'],
        'Cambodian' => ['ar' => 'كمبوديا', 'en' => 'Cambodia'],
        'Cameroonian' => ['ar' => 'الكاميرون', 'en' => 'Cameroon'],
        'Canadian' => ['ar' => 'كندا', 'en' => 'Canada'],
        'Chadian' => ['ar' => 'تشاد', 'en' => 'Chad'],
        'Chilean' => ['ar' => 'تشيلي', 'en' => 'Chile'],
        'Chinese' => ['ar' => 'الصين', 'en' => 'China'],
        'Colombian' => ['ar' => 'كولومبيا', 'en' => 'Colombia'],
        'Comoran' => ['ar' => 'جزر القمر', 'en' => 'Comoros'],
        'Congolese' => ['ar' => 'الكونغو', 'en' => 'Congo'],
        'Costa Rican' => ['ar' => 'كوستاريكا', 'en' => 'Costa Rica'],
        'Croatian' => ['ar' => 'كرواتيا', 'en' => 'Croatia'],
        'Cuban' => ['ar' => 'كوبا', 'en' => 'Cuba'],
        'Cypriot' => ['ar' => 'قبرص', 'en' => 'Cyprus'],
        'Czech' => ['ar' => 'جمهورية التشيك', 'en' => 'Czech Republic'],
        'Danish' => ['ar' => 'الدانمارك', 'en' => 'Denmark'],
        'Djiboutian' => ['ar' => 'جيبوتي', 'en' => 'Djibouti'],
        'Dominican' => ['ar' => 'دومينيكا', 'en' => 'Dominica'],
        'Ecuadorian' => ['ar' => 'الإكوادور', 'en' => 'Ecuador'],
        'Egyptian' => ['ar' => 'مصر', 'en' => 'Egypt'],
        'Salvadoran' => ['ar' => 'السلفادور', 'en' => 'El Salvador'],
        'Equatorial Guinean' => ['ar' => 'غينيا الاستوائية', 'en' => 'Equatorial Guinea'],
        'Eritrean' => ['ar' => 'إريتريا', 'en' => 'Eritrea'],
        'Estonian' => ['ar' => 'إستونيا', 'en' => 'Estonia'],
        'Ethiopian' => ['ar' => 'إثيوبيا', 'en' => 'Ethiopia'],
        'Fijian' => ['ar' => 'فيجي', 'en' => 'Fiji'],
        'Finnish' => ['ar' => 'فنلندا', 'en' => 'Finland'],
        'French' => ['ar' => 'فرنسا', 'en' => 'France'],
        'Gabonese' => ['ar' => 'الغابون', 'en' => 'Gabon'],
        'Gambian' => ['ar' => 'غامبيا', 'en' => 'Gambia'],
        'Georgian' => ['ar' => 'جورجيا', 'en' => 'Georgia'],
        'German' => ['ar' => 'ألمانيا', 'en' => 'Germany'],
        'Ghanaian' => ['ar' => 'غانا', 'en' => 'Ghana'],
        'Greek' => ['ar' => 'اليونان', 'en' => 'Greece'],
        'Grenadian' => ['ar' => 'غرينادا', 'en' => 'Grenada'],
        'Guatemalan' => ['ar' => 'غواتيمالا', 'en' => 'Guatemala'],
        'Guinean' => ['ar' => 'غينيا', 'en' => 'Guinea'],
        'Bissau-Guinean' => ['ar' => 'غينيا بيساو', 'en' => 'Guinea-Bissau'],
        'Guyanese' => ['ar' => 'غيانا', 'en' => 'Guyana'],
        'Haitian' => ['ar' => 'هايتي', 'en' => 'Haiti'],
        'Honduran' => ['ar' => 'هندوراس', 'en' => 'Honduras'],
        'Hungarian' => ['ar' => 'هنغاريا', 'en' => 'Hungary'],
        'Icelandic' => ['ar' => 'آيسلندا', 'en' => 'Iceland'],
        'Indian' => ['ar' => 'الهند', 'en' => 'India'],
        'Indonesian' => ['ar' => 'إندونيسيا', 'en' => 'Indonesia'],
        'Iranian' => ['ar' => 'إيران', 'en' => 'Iran'],
        'Iraqi' => ['ar' => 'العراق', 'en' => 'Iraq'],
        'Irish' => ['ar' => 'أيرلندا', 'en' => 'Ireland'],
        'Italian' => ['ar' => 'إيطاليا', 'en' => 'Italy'],
        'Jamaican' => ['ar' => 'جامايكا', 'en' => 'Jamaica'],
        'Japanese' => ['ar' => 'اليابان', 'en' => 'Japan'],
        'Jordanian' => ['ar' => 'الأردن', 'en' => 'Jordan'],
        'Kazakh' => ['ar' => 'كازاخستان', 'en' => 'Kazakhstan'],
        'Kenyan' => ['ar' => 'كينيا', 'en' => 'Kenya'],
        'I-Kiribati' => ['ar' => 'كيريباتي', 'en' => 'Kiribati'],
        'North Korean' => ['ar' => 'كوريا الشمالية', 'en' => 'North Korea'],
        'South Korean' => ['ar' => 'كوريا الجنوبية', 'en' => 'South Korea'],
        'Kosovar' => ['ar' => 'كوسوفو', 'en' => 'Kosovo'],
        'Kuwaiti' => ['ar' => 'الكويت', 'en' => 'Kuwait'],
        'Kyrgyz' => ['ar' => 'قرغيزستان', 'en' => 'Kyrgyzstan'],
        'Laotian' => ['ar' => 'لاوس', 'en' => 'Laos'],
        'Latvian' => ['ar' => 'لاتفيا', 'en' => 'Latvia'],
        'Lebanese' => ['ar' => 'لبنان', 'en' => 'Lebanon'],
        'Basotho' => ['ar' => 'ليسوتو', 'en' => 'Lesotho'],
        'Liberian' => ['ar' => 'ليبيريا', 'en' => 'Liberia'],
        'Libyan' => ['ar' => 'ليبيا', 'en' => 'Libya'],
        'Liechtensteiner' => ['ar' => 'ليختنشتاين', 'en' => 'Liechtenstein'],
        'Lithuanian' => ['ar' => 'ليتوانيا', 'en' => 'Lithuania'],
        'Luxembourger' => ['ar' => 'لوكسمبورغ', 'en' => 'Luxembourg'],
        'Malagasy' => ['ar' => 'مدغشقر', 'en' => 'Madagascar'],
        'Malawian' => ['ar' => 'مالاوي', 'en' => 'Malawi'],
        'Malaysian' => ['ar' => 'ماليزيا', 'en' => 'Malaysia'],
        'Maldivian' => ['ar' => 'المالديف', 'en' => 'Maldives'],
        'Malian' => ['ar' => 'مالي', 'en' => 'Mali'],
        'Maltese' => ['ar' => 'مالطا', 'en' => 'Malta'],
        'Marshallese' => ['ar' => 'جزر مارشال', 'en' => 'Marshall Islands'],
        'Mauritanian' => ['ar' => 'موريتانيا', 'en' => 'Mauritania'],
        'Mauritian' => ['ar' => 'موريشيوس', 'en' => 'Mauritius'],
        'Mexican' => ['ar' => 'المكسيك', 'en' => 'Mexico'],
        'Micronesian' => ['ar' => 'ميكرونيزيا', 'en' => 'Micronesia'],
        'Moldovan' => ['ar' => 'مولدوفا', 'en' => 'Moldova'],
        'Monacan' => ['ar' => 'موناكو', 'en' => 'Monaco'],
        'Mongolian' => ['ar' => 'منغوليا', 'en' => 'Mongolia'],
        'Montenegrin' => ['ar' => 'الجبل الأسود', 'en' => 'Montenegro'],
        'Moroccan' => ['ar' => 'المغرب', 'en' => 'Morocco'],
        'Mozambican' => ['ar' => 'موزمبيق', 'en' => 'Mozambique'],
        'Burmese' => ['ar' => 'ميانمار', 'en' => 'Myanmar'],
        'Namibian' => ['ar' => 'ناميبيا', 'en' => 'Namibia'],
        'Nauruan' => ['ar' => 'ناورو', 'en' => 'Nauru'],
        'Nepali' => ['ar' => 'نيبال', 'en' => 'Nepal'],
        'Dutch' => ['ar' => 'هولندا', 'en' => 'Netherlands'],
        'New Zealander' => ['ar' => 'نيوزيلندا', 'en' => 'New Zealand'],
        'Nicaraguan' => ['ar' => 'نيكاراغوا', 'en' => 'Nicaragua'],
        'Nigerien' => ['ar' => 'النيجر', 'en' => 'Niger'],
        'Nigerian' => ['ar' => 'نيجيريا', 'en' => 'Nigeria'],
        'Macedonian' => ['ar' => 'مقدونيا الشمالية', 'en' => 'North Macedonia'],
        'Norwegian' => ['ar' => 'النرويج', 'en' => 'Norway'],
        'Omani' => ['ar' => 'عمان', 'en' => 'Oman'],
        'Pakistani' => ['ar' => 'باكستان', 'en' => 'Pakistan'],
        'Palauan' => ['ar' => 'بالاو', 'en' => 'Palau'],
        'Palestinian' => ['ar' => 'فلسطين', 'en' => 'Palestine'],
        'Panamanian' => ['ar' => 'بنما', 'en' => 'Panama'],
        'Papua New Guinean' => ['ar' => 'بابوا غينيا الجديدة', 'en' => 'Papua New Guinea'],
        'Paraguayan' => ['ar' => 'باراغواي', 'en' => 'Paraguay'],
        'Peruvian' => ['ar' => 'بيرو', 'en' => 'Peru'],
        'Filipino' => ['ar' => 'الفلبين', 'en' => 'Philippines'],
        'Polish' => ['ar' => 'بولندا', 'en' => 'Poland'],
        'Portuguese' => ['ar' => 'البرتغال', 'en' => 'Portugal'],
        'Qatari' => ['ar' => 'قطر', 'en' => 'Qatar'],
        'Romanian' => ['ar' => 'رومانيا', 'en' => 'Romania'],
        'Russian' => ['ar' => 'روسيا', 'en' => 'Russia'],
        'Rwandan' => ['ar' => 'رواندا', 'en' => 'Rwanda'],
        'Kittitian' => ['ar' => 'سانت كيتس ونيفيس', 'en' => 'Saint Kitts and Nevis'],
        'Saint Lucian' => ['ar' => 'سانت لوسيا', 'en' => 'Saint Lucia'],
        'Vincentian' => ['ar' => 'سانت فنسنت وجزر غرينادين', 'en' => 'Saint Vincent and the Grenadines'],
        'Samoan' => ['ar' => 'ساموا', 'en' => 'Samoa'],
        'Sammarinese' => ['ar' => 'سان مارينو', 'en' => 'San Marino'],
        'Sao Tomean' => ['ar' => 'ساو تومي وبرينسيب', 'en' => 'Sao Tome and Principe'],
        'Saudi' => ['ar' => 'المملكة العربية السعودية', 'en' => 'Saudi Arabia'],
        'Senegalese' => ['ar' => 'السنغال', 'en' => 'Senegal'],
        'Serbian' => ['ar' => 'صربيا', 'en' => 'Serbia'],
        'Seychellois' => ['ar' => 'سيشيل', 'en' => 'Seychelles'],
        'Sierra Leonean' => ['ar' => 'سيراليون', 'en' => 'Sierra Leone'],
        'Singaporean' => ['ar' => 'سنغافورة', 'en' => 'Singapore'],
        'Slovak' => ['ar' => 'سلوفاكيا', 'en' => 'Slovakia'],
        'Slovenian' => ['ar' => 'سلوفينيا', 'en' => 'Slovenia'],
        'Solomon Islander' => ['ar' => 'جزر سليمان', 'en' => 'Solomon Islands'],
        'Somali' => ['ar' => 'الصومال', 'en' => 'Somalia'],
        'South African' => ['ar' => 'جنوب أفريقيا', 'en' => 'South Africa'],
        'South Sudanese' => ['ar' => 'جنوب السودان', 'en' => 'South Sudan'],
        'Spanish' => ['ar' => 'إسبانيا', 'en' => 'Spain'],
        'Sri Lankan' => ['ar' => 'سريلانكا', 'en' => 'Sri Lanka'],
        'Sudanese' => ['ar' => 'السودان', 'en' => 'Sudan'],
        'Surinamese' => ['ar' => 'سورينام', 'en' => 'Suriname'],
        'Swedish' => ['ar' => 'السويد', 'en' => 'Sweden'],
        'Swiss' => ['ar' => 'سويسرا', 'en' => 'Switzerland'],
        'Syrian' => ['ar' => 'سوريا', 'en' => 'Syria'],
        'Taiwanese' => ['ar' => 'تايوان', 'en' => 'Taiwan'],
        'Tajik' => ['ar' => 'طاجيكستان', 'en' => 'Tajikistan'],
        'Tanzanian' => ['ar' => 'تنزانيا', 'en' => 'Tanzania'],
        'Thai' => ['ar' => 'تايلاند', 'en' => 'Thailand'],
        'Timorese' => ['ar' => 'تيمور الشرقية', 'en' => 'Timor-Leste'],
        'Togolese' => ['ar' => 'توغو', 'en' => 'Togo'],
        'Tongan' => ['ar' => 'تونغا', 'en' => 'Tonga'],
        'Trinidadian' => ['ar' => 'ترينيداد وتوباغو', 'en' => 'Trinidad and Tobago'],
        'Tunisian' => ['ar' => 'تونس', 'en' => 'Tunisia'],
        'Turkish' => ['ar' => 'تركيا', 'en' => 'Turkey'],
        'Turkmen' => ['ar' => 'تركمانستان', 'en' => 'Turkmenistan'],
        'Tuvaluan' => ['ar' => 'توفالو', 'en' => 'Tuvalu'],
        'Ugandan' => ['ar' => 'أوغندا', 'en' => 'Uganda'],
        'Ukrainian' => ['ar' => 'أوكرانيا', 'en' => 'Ukraine'],
        'Emirati' => ['ar' => 'الإمارات العربية المتحدة', 'en' => 'United Arab Emirates'],
        'British' => ['ar' => 'المملكة المتحدة', 'en' => 'United Kingdom'],
        'Uruguayan' => ['ar' => 'أوروغواي', 'en' => 'Uruguay'],
        'Uzbek' => ['ar' => 'أوزبكستان', 'en' => 'Uzbekistan'],
        'Ni-Vanuatu' => ['ar' => 'فانواتو', 'en' => 'Vanuatu'],
        'Venezuelan' => ['ar' => 'فنزويلا', 'en' => 'Venezuela'],
        'Vietnamese' => ['ar' => 'فيتنام', 'en' => 'Vietnam'],
        'Yemeni' => ['ar' => 'اليمن', 'en' => 'Yemen'],
        'Zambian' => ['ar' => 'زامبيا', 'en' => 'Zambia'],
        'Zimbabwean' => ['ar' => 'زيمبابوي', 'en' => 'Zimbabwe'],

        // Common Aliases in Arabic to English
        'السعودية' => ['ar' => 'المملكة العربية السعودية', 'en' => 'Saudi Arabia'],
        'امريكا' => ['ar' => 'الولايات المتحدة', 'en' => 'United States'],
        'بريطانيا' => ['ar' => 'المملكة المتحدة', 'en' => 'United Kingdom'],
    ];
}

function getNationalityData($input)
{
    if (empty($input) || $input === '---') {
        return ['ar' => '---', 'en' => '---'];
    }

    $map = getNationalityMap();

    // Direct match (case-insensitive)
    foreach ($map as $key => $data) {
        if (strcasecmp($input, $key) === 0 || $input === $data['ar']) {
            return $data;
        }
    }

    // Partial match (if input is something like "Saudi Arabia" and key is "Saudi")
    foreach ($map as $key => $data) {
        if (stripos($input, $key) !== false || stripos($data['ar'], $input) !== false) {
            return $data;
        }
    }

    // Return input as fallback if not found
    return ['ar' => $input, 'en' => $input];
}
